spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_persona
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

#Variable de entorno
server:
  port: 9000

